# Generated by Django 2.2.6 on 2019-11-04 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191104_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 4, 6, 57, 43, 205656, tzinfo=utc)),
        ),
    ]
